export const section: string;
export const title: string;
export const empty: string;
export const isLoading: string;
export const cart: string;
export const cartItem: string;
export const image: string;
export const nameAndPrice: string;
export const removeButton: string;
